[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
<<<<<<< HEAD
=======

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[build.environment]

[context.production.branch-deploy]
    command = "mv robots-disallow.txt robots.txt"


[context.production]
    command = "mv robots-production.txt robots.txt"
>>>>>>> d92de98e1346ae1ab6207cb6cc821250e306f425
